apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflow.airflow.configSecretsName }}
data:
  {{- if .Release.IsInstall }}
  fernet-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  fernet-key: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.airflow.configSecretsName )).data "AIRFLOW__CORE__FERNET_KEY" }}
  {{ end }}