apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.airflow.airflow.configSecretsName }}
data:
  {{- if or .Release.IsInstall (not ( lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.airflow.configSecretsName ) ))  }}
  fernet-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  fernet-key: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.airflow.airflow.configSecretsName )).data "fernet-key" }}
  {{ end }}