apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "roger.fullname" . }}-airflow-user-create
spec:
  template:
    metadata:
      name: {{ include "roger.fullname" . }}-airflow-user-create
    spec:
      restartPolicy: Never
      volumes:
        - name: airflow-webserver-config
          configMap:
            name: airflow-webserver-config
            defaultMode: 0777
      containers:
        - name: init-db
          image: {{ .Values.airflow.airflow.image.repository}}:{{ .Values.airflow.airflow.image.tag }}
          command:
          - "/opt/users_create.sh"
          volumeMounts:
            - name: airflow-webserver-config
              subPath: users_create.sh
              mountPath: "/opt/users_create.sh"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            # Ref's appstore django admin user name and password.
            - name: ADMIN_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-appstore
                  key: APPSTORE_DJANGO_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-appstore
                  key: APPSTORE_DJANGO_PASSWORD
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-config-secrets
                  key: fernet-key
