apiVersion: v1
entries:
  ambassador:
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-25T18:47:04.12352-05:00"
    description: A Helm chart for Kubernetes
    digest: 411a1cc17debf4cbcbf39a124fcd13c2bbbe5d2bb3cb83b16b733e37fecaaff7
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-25T18:47:04.123113-05:00"
    description: A Helm chart for Kubernetes
    digest: bbbeea03857ddaf7cba8d9b1fb5e44942c48de0ab98311307cc7ac5c0f53ce83
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-25T18:47:04.121842-05:00"
    description: A Helm chart for Kubernetes
    digest: 0b9c00aa87a11e8b95837315512466ee29e21b139dbb908b1145cbcff948c666
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.1.tgz
    version: 0.1.1
  appstore:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.124185-05:00"
    description: A Helm chart for Kubernetes
    digest: 67e1a1477e45790bcfd49c6fafc90b1705687ba66eb46ee7f2fc7eeebc6d72bd
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.130279-05:00"
    description: A Helm chart for Kubernetes
    digest: 3d908cff9760f7f3a69d269e8af31fc4c633e93411d9304bf835d9fb1f6323a5
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.128482-05:00"
    description: A Helm chart for Kubernetes
    digest: 8d721efb24e10cd2b778c4ecb941a1d48ab45299cf527c0d23c9ec6c937c29f3
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.127225-05:00"
    description: A Helm chart for Kubernetes
    digest: 9a2bf6569bb2e7fdc0d5265e0c71f36c6bd2e0c697ca669cf0de205312026d3b
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.125321-05:00"
    description: A Helm chart for Kubernetes
    digest: abb5e5573cb3621565470f32142905b263721e12e288137b03614dc99c01ab43
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.5.tgz
    version: 0.1.5
  backup-pvc-cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-01-25T18:47:04.133042-05:00"
    description: A Helm chart for Kubernetes
    digest: a3e4f2a4432c71b024f0d224e23323e76d0f55d76a5bf38fffcc5a213deeeaca
    name: backup-pvc-cronjob
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/backup-pvc-cronjob-0.1.0.tgz
    version: 0.1.0
  dug:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.143615-05:00"
    description: Helm chart for dug
    digest: 2b6d89cfbebc591124c3cd139ed4efc8074f5ea0daabf1a3c70ff9fdbf166e55
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.142674-05:00"
    description: Helm chart for dug
    digest: f732fcca007daefe38081516b09c400693197312b9a7e8f9bca81c898964dcec
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.140952-05:00"
    description: Helm chart for dug
    digest: 9c7847838f5871917a7330b620c7f5bf7f9b2092c625ad6485d3688e8e7dbddf
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.13914-05:00"
    description: Helm chart for dug
    digest: b745a01f3dd1b7c7c489bd4563ac0f8cb553f6ab554216d3780786dd3ab5bbce
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.136813-05:00"
    description: Helm chart for dug
    digest: 7634b696743e704d4400a70ab2e405bd6ee87329ced02833b674f245272df770
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.135424-05:00"
    description: Helm chart for dug
    digest: ee2d1d87f78e9f4185a4f8813ae61d470b1986687a9f3b4e46f7c3e45e26f3a6
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.2.tgz
    version: 0.2.2
  helx:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.161465-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 2e96633b1934ba21ad6d3f8f79d59b76295709055b9ffd2bb60f269e81a01851
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.18.tgz
    version: 0.2.18
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.157284-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: ca1aea2b70c1e82aa127474bb3e4b948977defba196f70d4bbd94e50c81e6175
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.16.tgz
    version: 0.2.16
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.153139-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: f0c3463a04aa8e39bc497f688058b97bf5bab435c37151077b5ca10bebbb560b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.15.tgz
    version: 0.2.15
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.149036-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 8559f9fb13687cd318b7b731c548c3c42609bdae2f3d6b762c96196602aa5d80
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.13.tgz
    version: 0.2.13
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.178146-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 88cd59a18a77e8cc73ba03c3811cbef741c39cd2777dd4b04efaaab66b7a2861
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.174071-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 564d847042553619fc1f9ce27999da37981575991101c0fe9c896e99913c7ec5
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.169535-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 34eb97f6f34e44cc78c59dc648823519530c38413d684d4637fb9a03b2d7754b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.165267-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: bbb4a31b706eb80035554ccbec5785881035afc620f67a238914d2405880e4bc
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.6.tgz
    version: 0.2.6
  nfs-server:
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-25T18:47:04.179829-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: 7b8913b36c4ec52aa52d9ef3d38dacf43790e1515f098049adf28facfeedf3aa
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-25T18:47:04.179433-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: c74fee541cb7750b2e7a927e044310711979ff43a08510e51004efd4e23973bb
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-25T18:47:04.178701-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: 3da240f5b70d1daa0e35a8045f32055a86fff2a78ce1ec1c6297f58a6cf109ac
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.0.tgz
    version: 0.2.0
  nfsrods:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.180901-05:00"
    description: A standalone NFSv4.1 server (via nfs4j) with a Virtual File System
      implementation supporting the iRODS Data Management Platform.
    digest: 511de0e1d5caa62d833ef843c377657ea9876f3ec1b5e65eca6d90e9c38f29f7
    name: nfsrods
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfsrods-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.18046-05:00"
    description: A Helm chart for Kubernetes
    digest: aafd68ffcfa53d50f07e250e8247540e025fcab1b0c6a23bd08166bb85c867f9
    name: nfsrods
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfsrods-0.1.2.tgz
    version: 0.1.2
  nginx:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.183428-05:00"
    description: A Helm chart for Kubernetes
    digest: 03be74086067492937c46ecaff1551f832af322a5a48da3fb098f6b11c2d891c
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.181995-05:00"
    description: A Helm chart for Kubernetes
    digest: 54a8a4ca07bb8b30e9af033faf6f90cec00b62a28565bdbd625e82d01e883a60
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-25T18:47:04.181428-05:00"
    description: A Helm chart for Kubernetes
    digest: 9c5f4e86818bc1bd3630131b049c45a487848cd56b5da86f6780ef7b5f7083fe
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.5.tgz
    version: 0.1.5
  tycho-api:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.186452-05:00"
    description: A Helm chart for Kubernetes
    digest: 4b48b749389f7f4d1d0a41969959885bd958d870cfdd9b4eb94f0eabe86f2bc2
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.185754-05:00"
    description: A Helm chart for Kubernetes
    digest: d7ee15b095a274493b4192271ad91f50abee43aa67f1dcee041e170aa372a095
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.185123-05:00"
    description: A Helm chart for Kubernetes
    digest: c1ffd3174b21af041a3a5438bdd72ac6c7b9250887177a0385e7752e578a3d8b
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.184629-05:00"
    description: A Helm chart for Kubernetes
    digest: 98eca65de0a5d42f6f6ddc6557b0f3ef06aeca8b601d5d7f0b43f5740554d4d8
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-25T18:47:04.184005-05:00"
    description: A Helm chart for Kubernetes
    digest: aa4d2366914d00c03f7aca9002ab9506a7fd3f8d9993d2cfcd950dc1967c5528
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.5.tgz
    version: 0.1.5
generated: "2021-01-25T18:47:04.118173-05:00"
