apiVersion: v1
entries:
  ambassador:
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-21T15:12:51.06513-05:00"
    description: A Helm chart for Kubernetes
    digest: 35d395d118942ddf3709f369a18405655f9b79f06c860fa830ba8af2acb8d688
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-21T15:12:51.064413-05:00"
    description: A Helm chart for Kubernetes
    digest: bbbeea03857ddaf7cba8d9b1fb5e44942c48de0ab98311307cc7ac5c0f53ce83
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-21T15:12:51.063818-05:00"
    description: A Helm chart for Kubernetes
    digest: 0b9c00aa87a11e8b95837315512466ee29e21b139dbb908b1145cbcff948c666
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.1.tgz
    version: 0.1.1
  appstore:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.069991-05:00"
    description: A Helm chart for Kubernetes
    digest: 83c288b826fae77055f62eeed72185a9a5c144a7a4a67d96d5b00caaac527658
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.06871-05:00"
    description: A Helm chart for Kubernetes
    digest: 8d721efb24e10cd2b778c4ecb941a1d48ab45299cf527c0d23c9ec6c937c29f3
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.067521-05:00"
    description: A Helm chart for Kubernetes
    digest: 9a2bf6569bb2e7fdc0d5265e0c71f36c6bd2e0c697ca669cf0de205312026d3b
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.066176-05:00"
    description: A Helm chart for Kubernetes
    digest: abb5e5573cb3621565470f32142905b263721e12e288137b03614dc99c01ab43
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.5.tgz
    version: 0.1.5
  backup-pvc-cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-01-21T15:12:51.070545-05:00"
    description: A Helm chart for Kubernetes
    digest: a3e4f2a4432c71b024f0d224e23323e76d0f55d76a5bf38fffcc5a213deeeaca
    name: backup-pvc-cronjob
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/backup-pvc-cronjob-0.1.0.tgz
    version: 0.1.0
  dug:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.082775-05:00"
    description: Helm chart for dug
    digest: b57582f508302d36081fa7baff36fe90d7f9a8d81a5664854b6a4587e9b8953d
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.0803-05:00"
    description: Helm chart for dug
    digest: f732fcca007daefe38081516b09c400693197312b9a7e8f9bca81c898964dcec
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.078812-05:00"
    description: Helm chart for dug
    digest: 9c7847838f5871917a7330b620c7f5bf7f9b2092c625ad6485d3688e8e7dbddf
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.076439-05:00"
    description: Helm chart for dug
    digest: b745a01f3dd1b7c7c489bd4563ac0f8cb553f6ab554216d3780786dd3ab5bbce
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.07476-05:00"
    description: Helm chart for dug
    digest: 7634b696743e704d4400a70ab2e405bd6ee87329ced02833b674f245272df770
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.071603-05:00"
    description: Helm chart for dug
    digest: ee2d1d87f78e9f4185a4f8813ae61d470b1986687a9f3b4e46f7c3e45e26f3a6
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.2.tgz
    version: 0.2.2
  helx:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.094413-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: f0c3463a04aa8e39bc497f688058b97bf5bab435c37151077b5ca10bebbb560b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.15.tgz
    version: 0.2.15
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.087316-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 8559f9fb13687cd318b7b731c548c3c42609bdae2f3d6b762c96196602aa5d80
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.13.tgz
    version: 0.2.13
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.111803-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 88cd59a18a77e8cc73ba03c3811cbef741c39cd2777dd4b04efaaab66b7a2861
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.108115-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 564d847042553619fc1f9ce27999da37981575991101c0fe9c896e99913c7ec5
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.104262-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 34eb97f6f34e44cc78c59dc648823519530c38413d684d4637fb9a03b2d7754b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.098492-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: bbb4a31b706eb80035554ccbec5785881035afc620f67a238914d2405880e4bc
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.6.tgz
    version: 0.2.6
  nfs-server:
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-21T15:12:51.112893-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: 4398e28116319c3386afb67309f479d106b0eda230679c1b8a6e5108abba58fd
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-21T15:12:51.112478-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: 3da240f5b70d1daa0e35a8045f32055a86fff2a78ce1ec1c6297f58a6cf109ac
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.0.tgz
    version: 0.2.0
  nfsrods:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.113535-05:00"
    description: A Helm chart for Kubernetes
    digest: f98a1efcb46109c1363d92d8f9a1574c8464d7d2d7d523b0daef63e1bffe0c81
    name: nfsrods
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfsrods-0.1.2.tgz
    version: 0.1.2
  nginx:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.116777-05:00"
    description: A Helm chart for Kubernetes
    digest: 80c9dedbae55be5dd9019f5a7b431d07d1a9bac16c48cc31d1977651bcaa6b31
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.115796-05:00"
    description: A Helm chart for Kubernetes
    digest: 54a8a4ca07bb8b30e9af033faf6f90cec00b62a28565bdbd625e82d01e883a60
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-21T15:12:51.114065-05:00"
    description: A Helm chart for Kubernetes
    digest: 9c5f4e86818bc1bd3630131b049c45a487848cd56b5da86f6780ef7b5f7083fe
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.5.tgz
    version: 0.1.5
  tycho-api:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.119026-05:00"
    description: A Helm chart for Kubernetes
    digest: ab3d435d78e19147df0479a76b595c9cfc19ebcf30efff08294b8004d9dba533
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.118321-05:00"
    description: A Helm chart for Kubernetes
    digest: c1ffd3174b21af041a3a5438bdd72ac6c7b9250887177a0385e7752e578a3d8b
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.117861-05:00"
    description: A Helm chart for Kubernetes
    digest: 98eca65de0a5d42f6f6ddc6557b0f3ef06aeca8b601d5d7f0b43f5740554d4d8
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-21T15:12:51.117239-05:00"
    description: A Helm chart for Kubernetes
    digest: aa4d2366914d00c03f7aca9002ab9506a7fd3f8d9993d2cfcd950dc1967c5528
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.5.tgz
    version: 0.1.5
generated: "2021-01-21T15:12:51.06029-05:00"
