version: 0.0.1

build:
  name: conda-layer-master

app:
  name: conda-layer

code:
  primary_url:
    https://github.com/helxplatform/helx-hail.git
  secondary_url:
    null
  primary_app_path:
    "."
  primary_requirements_path:
    null
  secondary_requirements_path:
    null
  branch:
    master
  prebuild:
    default
  build:
    default
  test:
    default

docker:
  org:
    helxplatform
  primary_repo:
    conda-layer
  secondary_repo:
    null
  docker_fn:
    null
  primary_docker_dir:
    docker/conda-layer
  secondary_docker_dir:
    null
  build_args:
    null

test:
  cmd_path:
    null
  cmd_args:
    null
  datafile:
    null
