{{- if .Values.ingress.create }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{ if .Values.SSL }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.SSL.nginxTLSSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "nginx.fullname" . }}
          servicePort: {{ .Values.service.httpPort }}
{{- end }}
