{{- if .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}
  annotations:
  {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- if .Values.ingress.traefikRouterTls }}
    traefik.ingress.kubernetes.io/router.tls: {{ .Values.ingress.traefikRouterTls }}
    {{- end }}
  {{- else }}
    []
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "nginx.fullname" . }}
          servicePort: {{ .Values.service.httpPort }}
{{- end }}
