apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.IP }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpTargetPort }}
    protocol: TCP
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- if .Values.SSL }}
  - name: https
    port: {{ .Values.service.httpsPort }}
    targetPort: {{ .Values.service.httpsTargetPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
