# Parent chart for HeLx.

ambassador:
  enabled: true
appstore:
  enabled: true
backup-pvc-cronjob:
  enabled: false
commonsshare:
  enabled: false
nfs-server:
  enabled: true
nfsrods:
  enabled: false
nginx:
  enabled: true
tycho-api:
  enabled: true
dug:
  enabled: true
