# Parent chart for HeLx.

ambassador:
  # -- enable/disable deployment of Ambassador
  enabled: true
appstore:
  # -- enable/disable deployment of appstore
  enabled: true
backup-pvc-cronjob:
  # -- enable/disable deployment of backup-pvc-cronjob
  enabled: false
dug:
  # -- enable/disable deployment of dug
  enabled: false
helx-monitoring:
  # -- enable/disable deployment of loki-stack and cost-analyzer
  enabled: false
image-utils:
  # -- enable/disable deployment of image-utils (imagepullsecret-patcher and
  # imagepuller)
  enabled: false
nfs-server:
  # -- enable/disable deployment of nfs-server
  enabled: true
nfsrods:
  # -- enable/disable deployment of nfsrods
  enabled: false
nginx:
  # -- enable/disable deployment of nginx
  enabled: true
tycho-api:
  # -- enable/disable deployment of tycho-api
  enabled: false
pod-reaper:
  # -- enable/disable deployment of pod-reaper
  enabled: true
redis:
  image:
    repository: redislabs/redisgraph
    tag: 2.2.14
  redis:
    command: "redis-server"
  clusterDomain: "blackbalsam-cluster"
  cluster:
    slaveCount: 1
  usePassword: true
  master:
    service:
      port: 6379
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
  slave:
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

roger:
  enabled: false

global:
  tycho_api_service_name: helx-tycho-api
  dug_web_service_name: helx-dug-web
  dug_search_client_service_name: helx-dug-search-client
  restartr_api_service_name: helx-restartr-api-service
  stdnfsPvc: stdnfs
  redis:
    existingSecret: redis-secret
    existingSecretPasswordKey: redis-password
