---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: inplace-reindex-dataverse-
  labels:
    app.kubernetes.io/name: reindex
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reindex
        app.kubernetes.io/part-of: dataverse
    spec:
      containers:
        - name: reindex
          image: giantswarm/tiny-tools
          command: ['sh', '-c',
            'curl -sS -f -X DELETE "http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}/api/admin/index/timestamps?unblock-key=${API_KEY}" &&
            curl -sS -f "http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}/api/admin/index/continue?unblock-key=${API_KEY}"']
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: dataverse-api
                  key: key
      initContainers:
        - name: check-solr-ready
          image: giantswarm/tiny-tools
          command: ['sh', '-c',
            'until curl -sS -f "http://${SOLR_SERVICE_HOST}:${SOLR_SERVICE_PORT}/solr/collection1/admin/ping" 2>&1 | grep "status.:.OK";
            do echo waiting for solr; sleep 3; done;']
        - name: check-dataverse-ready
          image: giantswarm/tiny-tools
          command: ['sh', '-c',
            'until curl -sS -f "http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}/robots.txt" -m 2 2>&1 > /dev/null;
            do echo waiting for dataverse; sleep 15; done;']
      volumes:
        - name: api-secret
          secret:
            secretName: dataverse-api
      restartPolicy: Never
  backoffLimit: 4
