elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.9.1
    pullPolicy: IfNotPresent
  app_name: dug-elasticsearch
  pvc_name: dug-elasticsearch-pvc
  certs_secret: elastic-certificates
  create_certs_secret: true
  service_name: dug-elasticsearch
  statefulset_name: dug-elasticsearch
  initial_master_name: dug-elasticsearch-0
  rest_port: 9200
  nodes_com_port: 9300
  storage_size: 5Gi
  # Specify a storageclass to use if not using the cluster default.
  # storage_class: standard
  db_user: elastic
  init_config_name: elasticsearch-initcontainer
  xmx: 2g
  xms: 2g
  cluster_name: dug-elasticsearch-cluster
  roles:
    master: "true"
    ingest: "true"
    data: "true"
  replica_count: 3
  liveness:
    initial_delay: 30
    check_interval: 10
neo4j:
  image:
    repository: bitnami/neo4j
    tag: 3.5.14
    pullPolicy: IfNotPresent
  app_name: dug-neo4j
  pvc_name: dug-neo4j-pvc
  service_name: dug-neo4j
  deployment_name: dug-neo4j
  http_port: 7474
  https_port: 7473
  bolt_port: 7687
  storage_size: 1G
  # storage_class: standard
  db_user: neo4j
redis:
  image:
    repository: bitnami/redis
    tag: 5.0.8
    pullPolicy: IfNotPresent
  app_name: dug-redis
  pvc_name: dug-redis-pvc
  service_name: dug-redis
  deployment_name: dug-redis
  storage_size: 5G
  # storage_class: standard
  redis_port: 6389
dug:
  image:
    repository: heliumdatastage/dug
    tag: 1.0.2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  app_name: dug-web
  service_name: dug-web
  deployment_name: dug-web
  api_port: 5551
  debug: false
  ambassador:
    search:
      map_name: dug-search
      prefix: /search
    search_kg:
      map_name: dug-search-kg
      prefix: /search_kg
  crawl_command: bin/dug crawl_by_tag --crawl-file data/topmed_variables_v1.0.csv
  # Add any extra environment variables not already defined in the chart.
  extraEnv: {}
secrets:
  name: dug-secrets
search_client:
  app_name: dug-search-client
  deployment_name: dug-search-client
  service_name: dug-search-client
  http_port: 80
  container_port: 8080
  image:
    repository: heliumdatastage/dug-search-client
    tag: 1.0.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  ambassador:
    ui:
      map_name: dug-ui
      prefix: /ui
  # Add any extra environment variables not already defined in the chart.
  extraEnv: {}
nboost:
  app_name: dug-nboost
  deployment_name: dug-nboost
  service_name: dug-nboost
  image:
    repository: koursaros/nboost
    tag: 0.3.9-pt
    pullPolicy: IfNotPresent
  api_port: 8000
  model: nboost/pt-biobert-base-msmarco

create_pvcs: true
