---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dataverse

bases:
  - solr
  - webapp

resources:
  - config/secrets.yaml

patchesStrategicMerge:
  - config/dataverse.yaml
