replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: tycho-api

serviceAccount:
  create: true
  name: tycho-api

service:
  type: ClusterIP
  port: 80
  ip_none: true

resources:
  limits:
     cpu: 100m
     memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi

image: heliumdatastage/tycho-api:1.0.2

# Set either useClusterRole or useRole to true.
useClusterRole: false
useRole: true

# Set to true, when using blackbalsam.
useSparkServiceAccount: true

# Specify a PV to use as HeLx's stdnfs.
stdnfsPvc: stdnfs
# Create Home directories
createHomeDirs: true

runAsRoot: true

# Variables for default volumes.
parent_dir: "/home"
subpath_dir: null
shared_dir: "shared"
