replicaCount: 1

image:
  repository: heliumdatastage/tycho-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 1.0.2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  name: tycho-api

serviceAccount:
  create: true
  name: tycho-api

service:
  type: ClusterIP
  port: 80
  ip_none: true

resources:
  limits:
     cpu: 100m
     memory: 256Mi
  requests:
     cpu: 50m
     memory: 128Mi

# Set either useClusterRole or useRole to true.
useClusterRole: false
useRole: true

# Set to true, when using blackbalsam.
useSparkServiceAccount: true

# Specify a PV to use as HeLx's stdnfs.
stdnfsPvc: stdnfs
# Create Home directories
createHomeDirs: true

runAsRoot: true

# Variables for default volumes.
parent_dir: "/home"
subpath_dir: null
shared_dir: "shared"

# Add any extra environment variables not already defined in the chart.
extraEnv: {}
