apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: {{ template "tycho-api.name" . }}
    app: {{ template "tycho-api.name" . }}
  name: {{ template "tycho-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ template "tycho-api.name" . }}
      app: {{ template "tycho-api.name" . }}
  template:
    metadata:
      labels:
        service: {{ template "tycho-api.name" . }}
        app: {{ template "tycho-api.name" . }}
    spec:
      containers:
      - command:
        - /usr/local/bin/gunicorn
        - --workers=2
        - --name=tycho
        - --timeout=600
        - tycho.api:app
        image: {{ .Values.image }}
        env:
        - name: CREATE_HOME_DIRS
          value: "{{- .Values.createHomeDirs }}"
        - name: STDNFS_PVC
          value: "{{ .Values.stdnfsPvc }}"
        - name: RUNASROOT
          value: "{{ .Values.runAsRoot }}"
        - name: PARENT_DIR
          value: "{{ .Values.parent_dir }}"
        {{- if .Values.subpath_dir }}
        - name: SUBPATH_DIR
          value: "{{ .Values.subpath_dir }}"
        {{- end }}
        - name: SHARED_DIR
          value: "{{ .Values.shared_dir }}"
        imagePullPolicy: "Always"
        name: {{ template "tycho-api.name" . }}
        ports:
        - containerPort: 8099
          protocol: TCP
      restartPolicy: Always
