apiVersion: v1
kind: Pod
metadata:
  labels:
    service: {{ template "tycho-api.name" . }}
    app: {{ template "tycho-api.name" . }}
  name: {{ template "tycho-api.name" . }}
spec:
  containers:
  - command:
    - /usr/local/bin/gunicorn
    - --workers=2
    - --name=tycho
    - --timeout=600
    - tycho.api:app
    image: {{ .Values.image }}
    env:
    - name: CREATE_HOME_DIRS
      value: {{ .Values.createHomeDirs }}
    - name: STDNFS_PVC
      value: {{ .Values.stdnfsPvc }}
    imagePullPolicy: "Always"
    name: {{ template "tycho-api.name" . }}
    ports:
    - containerPort: 8099
      protocol: TCP
    resources:
      requests:
        cpu: {{ .Values.resources.requests.cpu | quote }}
  restartPolicy: Always
