{{- if .Values.useRole }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tycho-api.name" . }}-access
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
    - configmaps
    - pods
    - secrets
    - services
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - "apps"
  resources:
    - deployments
    - deployments/rollback
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
    - deployments
    - deployments/rollback
    - deployments/scale
    - ingresses
    - replicasets
    - replicasets/scale
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  attributeRestrictions: null
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tycho-api.name" . }}-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "tycho-api.name" . }}-access
  apiGroup: rbac.authorization.k8s.io
{{- end }}
