{{- if .Values.useClusterRole }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tycho-api-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-access-admin
subjects:
  - kind: ServiceAccount
    name: tycho-api-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
