apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tranql.fullname" . }}-configmap
  labels:
    {{- include "tranql.labels" . | nindent 4 }}
data:
  conf.yml: |
    m: z
  schema.yml: |
    doc: |
      Schema configuration for tranql
    schema:
      redis:
        doc: |
          tranql is a knowledge graph built by aggregeting several kgx formatted knowledge graphs from several sources.
        url: "redis:"
        redis: true
        redis_connection_params:
          {{- if .Values.redis.enabled }}
          host: {{ include "tranql.redis.fullname" . }}
          port: {{ .Values.redis.redisPort }}
          {{- else }}
          host: {{ .Values.existingRedis.host }}
          port: {{ .Values.existingRedis.port }}
          {{- end }}
          # SET USERNAME and PASSWORD
          # via REDIS_USERNAME , REDIS_PASSWORD Env vars (i.e capitialize service name)
