---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/IQSS/dataverse-kubernetes/k8s/dataverse?ref=release

images:
  - name: iqss/dataverse-k8s
    newTag: "4.19"

patchesStrategicMerge:
  - patch-checkdb.yaml
  - patch-limits.yaml
