---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/IQSS/dataverse-kubernetes/k8s/solr?ref=release

images:
  - name: iqss/solr-k8s
    newName: heliumdatastage/solr-iqss
    newTag: "4.19"
