{{- if not .Values.appStorage.existingClaim }}
{{- if .Values.appStorage.claimName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appStorage.claimName }}
  labels:
    app: nginx-revproxy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appStorage.storageSize }}
  storageClassName: {{ .Values.appStorage.storageClass }}
{{- end }}
{{- end }}
