apiVersion: v1
kind: Secret
metadata:
  name: dicom-cloudtop-env
data:
  USER_HOME: {{ .Values.apps.DICOMCT_USER_HOME | b64enc }}
  USER_NAME: {{ .Values.apps.DICOMCT_USER_NAME | b64enc }}
  VNC_PW: {{ randAlphaNum 12 | b64enc | quote }}
