apiVersion: v1
kind: Secret
metadata:
  name: dicom-gh-env
data:
  USER_HOME: {{ .Values.apps.DICOMGH_USER_HOME }}
  USER_NAME: {{ .Values.apps.DICOMGH_USER_NAME }}
  VNC_PW: {{ .Values.apps.DICOMGH_VNC_PW }}
  CLIENT_ID: {{ .Values.apps.DICOMGH_GOOGLE_CLIENT_ID }}
