{{- if eq .Values.userStorage.createPVC true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.stdnfsPvc }}
  labels:
    {{- include "appstore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.userStorage.storageSize }}
  storageClassName: {{ .Values.userStorage.storageClass }}
{{- end }}
---
{{- if eq .Values.userStorage.nfs.createPV true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "appstore.fullname" . }}-user-storage-pv
spec:
  capacity:
    storage: {{ .Values.userStorage.storageSize }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  storageClassName: {{ .Values.userStorage.storageClass }}
  nfs:
    path: {{ .Values.userStorage.nfs.path }}
    server: {{ .Values.userStorage.nfs.server }}
{{- end }}
