apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.elastic.name }}
{{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.elastic.name ))) }}
stringData:
  username: {{ .Values.secrets.elastic.elastic_user }}
data:
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{ else }}
stringData:
  username: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.elastic.name )).data "username"}}
data:
  password: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.elastic.name )).data "password" }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis.name }}
data:
  {{- if or .Release.IsInstall ( not (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name ))) }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  password: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.secrets.redis.name )).data "password" }}
  {{ end }}