---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          command: ['sh', '-c',
            'until pg_isready -h dataverse-postgres-postgresql -p 5432;
            do echo waiting for database; sleep 3; done;']
