redis:
  image:
    repository: redislabs/redisgraph
    tag: 2.2.13
  redis:
    command: "redis-server"
  clusterDomain: "blackbalsam-cluster"
  cluster:
    slaveCount: 1
  usePassword: false
  master:
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
  slave:
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"


airflow:
  #
  # NOTE:
  # - This is intended to be a `custom-values.yaml` starting point for non-production deployment (like minikube)

  # External Dependencies:
  # - A PUBLIC git repo for DAGs: ssh://git@repo.example.com:my-airflow-dags.git
  #

  ###################################
  # Airflow - Common Configs
  ###################################
  airflow:
    ## the airflow executor type to use
    ##
    image:
      repository: renciorg/apache-airflow-1.10.14-python-3.8-git
      tag: latest
    #  executor: CeleryExecutor
    executor: KubernetesExecutor

    ## environment variables for the web/scheduler/worker Pods (for airflow configs)
    ##
    config:
      # Security
      AIRFLOW__CORE__SECURE_MODE: "True"
      AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__WEBSERVER__RBAC: "False"
      AIRFLOW__KUBERNETES__GIT_REPO: "ssh://git@github.com/helxplatform/roger.git"
      # https://airflow.apache.org/docs/apache-airflow/1.10.12/configurations-ref.html#git-ssh-key-secret-name
      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-secrets"
      # @TODO change this to master.
      AIRFLOW__KUBERNETES__GIT_BRANCH: "develop"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
      AIRFLOW__KUBERNETES__GIT_SYNC_DEST: "roger"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "roger"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "FALSE"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "renciorg/roger-executor"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "0.26"
      # DAGS
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW_BASE_URL: ""

      ## Disable noisy "Handling signal: ttou" Gunicorn log messages
      GUNICORN_CMD_ARGS: "--log-level WARNING"

    extraPipPackages:
      - Babel==2.8.0
      - biolink-model==1.2.5
      - biolinkml==1.5.8
      - redisgraph==2.1.5
      - git+https://github.com/RedisGraph/redisgraph-bulk-loader.git
      - flatten-dict
      - git+https://github.com/stevencox/kgx.git

    ###################################
    # Volumes
    ###################################
    extraVolumeMounts:
      - name: roger-data
        mountPath: /dags/roger/data

    ## extra volumes for the web/scheduler/worker Pods

    extraVolumes:
      - name: roger-data
        emptyDir: {}

    configSecretsName: airflow-config-secrets

    extraEnv:
      - name: AIRFLOW__CORE__FERNET_KEY
        valueFrom:
          secretKeyRef:
            # Same as airflow.configSecretsName
            name: airflow-config-secrets
            key: fernet-key



  ###################################
  # Airflow - WebUI Configs
  ###################################

  web:
    ## configs for the Service of the web Pods
    ##
    service:
      type: ClusterIP


  ###################################
  # Airflow - Worker Configs
  ###################################
  workers:
    ## the number of workers Pods to run
    ##
    replicas: 1

  ###################################
  # Airflow - DAGs Configs
  ###################################
  dags:
    ## configs for the DAG git repository & sync container
    ##
    git:
      ## url of the git repository
      url: "ssh://git@github.com/helxplatform/roger.git"

      ## the branch/tag/sha1 which we clone
      ##
      ref: develop

      ## the name of a pre-created secret containing files for ~/.ssh/
      ##
      ## NOTE:
      ## - this is ONLY RELEVANT for SSH git repos
      ## - the secret commonly includes files: id_rsa, id_rsa.pub, known_hosts
      ## - known_hosts is NOT NEEDED if `git.sshKeyscan` is true
      ##
      secret: airflow-git-keys

      ## the name of the private key file in your `git.secret`
      ##
      ## NOTE:
      ## - this is ONLY RELEVANT for PRIVATE SSH git repos
      ##
      privateKeyName: id_rsa

      ## the host name of the git repo
      ##
      ## NOTE:
      ## - this is ONLY REQUIRED for SSH git repos
      ##
      ## EXAMPLE:
      ##   repoHost: "github.com"
      ##
      repoHost: "github.com"

      ## the port of the git repo
      ## NOTE:
      ## - this is ONLY REQUIRED for SSH git repos
      ##
      repoPort: 22

      ## configs for the git-sync container
      gitSync:
        ## enable the git-sync sidecar container
        enabled: true
        ## the git sync interval in seconds
        refreshTime: 60
    installRequirments: true

  ###################################
  # Database - PostgreSQL Chart
  ###################################
  postgresql:
    enabled: true

  ###################################
  # Database - Redis Chart
  ###################################
  redis:
    enabled: false



tranql:
  image: renciorg/tranql-app
  imageTag: develop-test
  replicas: 1
  port: 8081
  gunicorn:
    workerCount: 4
    workerTimeout: 300
  service:
    type: ClusterIP


web:
  ambassador:
    tranql:
      prefix: /tranql
      map_name: tranql-amb
    airflowUI:
      prefix: /airflow
      map_name: airflow-ui-amb


