{{- if .Values.elasticsearch.create_certs_secret -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-script-configmap
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "4"
data:
  create_es_certs.sh: |
        yum -y install kubernetes-client && \
        elasticsearch-certutil ca --out /tmp/elastic-stack-ca.p12 --pass '' && \
        elasticsearch-certutil cert --name security-master --dns security-master --ca /tmp/elastic-stack-ca.p12 --pass '' --ca-pass '' --out /tmp/elastic-certificates.p12 && \
        kubectl -n {{ .Release.Namespace }} create secret generic {{ .Values.elasticsearch.certs_secret }} --from-file=/tmp/elastic-certificates.p12 && \
        rm -f /tmp/elastic-certificates.p12 /tmp/elastic-certificate.pem /tmp/elastic-certificate.crt /tmp/elastic-stack-ca.p12
{{- end }}
