{{- if .Values.elasticsearch.create_certs_secret -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dug.elasticsearch.fullname" . }}-pre-install-sa
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "1"
{{- end }}
