{{- if .Values.elasticsearch.create_certs_secret -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: delete-script-configmap
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "4"
data:
  delete_es_certs_secret.sh: |
        yum -y install kubernetes-client && \
        kubectl -n {{ .Release.Namespace }} delete secret {{ .Values.elasticsearch.certs_secret }} --ignore-not-found=true
{{- end }}
