{{- if .Values.elasticsearch.create_certs_secret -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dug.elasticsearch.fullname" . }}-secrets-rolebinding
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "3"
roleRef:
  kind: Role
  name: {{ include "dug.elasticsearch.fullname" . }}-secrets-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "dug.elasticsearch.fullname" . }}-pre-install-sa
{{- end }}
