apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.dug.nboost.app_name }}
  name: {{ .Values.dug.nboost.deployment_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dug.nboost.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dug.nboost.app_name }}
    spec:
      containers:
      - image: {{ .Values.dug.nboost.image.repository }}:{{ .Values.dug.nboost.image.tag }}
        imagePullPolicy: {{ .Values.dug.nboost.image.pullPolicy }}
        name: {{ .Values.dug.nboost.app_name }}-container
        ports:
          - containerPort: {{ .Values.dug.nboost.api_port }}
        args:
        - --model_dir={{ .Values.dug.nboost.model }}
