apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.neo4j.app_name }}
  name: {{ include "dug.neo4j.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.neo4j.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.neo4j.app_name }}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
        imagePullPolicy: {{ .Values.neo4j.image.pullPolicy }}
        name: {{ include "dug.neo4j.fullname" . }}-container
        env:
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: NEO4J_PASSWORD
        - name: NEO4J_HOST
          value: {{ .Values.neo4j.service.name }}
        resources:
          {{- toYaml .Values.neo4j.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /bitnami
          name: neo4j
        ports:
          - containerPort: {{ .Values.neo4j.http_port }}
          - containerPort: {{ .Values.neo4j.https_port }}
          - containerPort: {{ .Values.neo4j.bolt_port }}
      volumes:
      - name: neo4j
        persistentVolumeClaim:
          claimName: {{ .Values.neo4j.pvc_name }}
