apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.search_client.app_name }}
  name: {{ .Values.search_client.deployment_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.search_client.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.search_client.app_name }}
    spec:
      {{- with .Values.search_client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.search_client.image.repository }}:{{ .Values.search_client.image.tag }}
        imagePullPolicy: {{ .Values.search_client.image.pullPolicy }}
        name: {{ .Values.search_client.app_name }}-container
        ports:
          - containerPort: {{ .Values.search_client.container_port }}
