apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.web.app_name}}
  name: {{ include "dug.web.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.web.app_name}}
  template:
    metadata:
      labels:
        app: {{ .Values.web.app_name}}
    spec:
      {{- with .Values.web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        name: {{ include "dug.web.fullname" . }}-container
        env:
        - name: ELASTIC_API_HOST
          value: {{ .Values.elasticsearch.service.name }}
        - name: ELASTIC_API_PORT
          value: {{ .Values.elasticsearch.rest_port | quote }}
        - name: ELASTIC_USER
          value: {{ .Values.elasticsearch.db_user }}
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: ELASTIC_PASSWORD
        - name: NEO4J_HOST
          value: {{ .Values.neo4j.service.name }}
        - name: NEO4J_PORT
          value: {{ .Values.neo4j.http_port | quote }}
        - name: NEO4J_USER
          value: {{ .Values.neo4j.db_user }}
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: NEO4J_PASSWORD
        - name: REDIS_HOST
          value: {{ .Values.redis.service.name }}
        - name: REDIS_PORT
          value: {{ .Values.redis.redis_port | quote }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: REDIS_PASSWORD
        - name: NBOOST_API_HOST
          value: {{ .Values.nboost.service.name }}
        {{- range $key, $value := .Values.web.extraEnv }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.web.api_port }}
        command: ["/bin/bash", "-c", "/app/run-dug-and-crawl.sh"]
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        volumeMounts:
        - name: scripts-vol
          mountPath: /app
      volumes:
        - name: scripts-vol
          configMap:
            name: web-scripts-configmap
            defaultMode: 0775
