---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
spec:
  template:
    spec:
      containers:
        - name: dataverse
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: solr
spec:
  template:
    spec:
      containers:
        - name: solr
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
